### ISSUE TITLE
Playground stays disabled

### ISSUE THREAD

**Issue by scarlac** [graphql-python/graphene#195]
The "Playground" at http://graphene-python.org/playground/ does not work for me in Safari 9.1.1, Chrome 51 or Firefox 46. I am seeing a "disabled" view, meaning I see the UI with some demo text yet all 3 columns are dimmed/grayed out. Screenshot:
![screen shot 2016-06-05 at 20 52 23](https://cloud.githubusercontent.com/assets/895369/15807475/71d19758-2b5f-11e6-860f-424174dec2d1.png)

Not entirely sure if it's appropriate to post an issue here that's related to the website, so feel free to remove it if it's off topic.

**Comment by syrusakbary** [comment]
Thanks for the ping. This is now fixed :)

**Comment by emekanw** [comment]
This issue is not fixed.
<img width="1396" alt="screen shot 2016-08-31 at 9 18 38 pm" src="https://cloud.githubusercontent.com/assets/1414830/18151987/cfaa3164-6fc0-11e6-9651-75cc18bf1370.png">

**Comment by syrusakbary** [comment]
@emekanw it takes some time to load.
If is still not loading would be very helpful know your browser and version. :)

**Comment by ewdicus** [comment]
@syrusakbary The playground was working great a few days ago, but It's currently stuck loading. (I've left it open for several minutes with no change.) The output in the console is:

<img width="572" alt="screen shot 2017-04-26 at 3 16 08 pm" src="https://cloud.githubusercontent.com/assets/1026059/25459499/60814e24-2a93-11e7-9f73-7075ee1435f2.png">

I'm on Chrome 58.0.3029.81 (64-bit)

**Comment by syrusakbary** [comment]
Thanks for posting, will review soon! :)
