### ISSUE TITLE
Saving null value for nullable fields

### ISSUE THREAD

**Issue by prokofiev** [graphql-python/graphene#280]
I had a problem saving the null values in the mutations. Is it possible to implement functionality to `get_argument_values` function could distinguish passed null value and not passed value?
I think it can be implemented similar to the `executor.ececute_fields` using Undefined.

**Comment by syrusakbary** [comment]
Hi @prokofiev!

You can actually use the `default_value` in the Argument and set another default than `None`.

So currently you can do:
```python
class Undefined(object): pass

class Query(graphene.ObjectType):
    field = graphene.String(
        input=graphene.String(default_value=Undefined)
    )
```

It might be interesting to set `Undefined` as default_value in a `GraphQLArgument` in `graphql-core` instead of `None`, but probably this is more that we have to investigate a little bit further :)

**Comment by prokofiev** [comment]
Hi @syrusakbary !
Thanks for answer, but `default_value`  will not be able to solve my problem.
I try to describe the problem in more detail:

```python
class Foo(models.Model):
    ''' Example model with nullable field '''
    not_null = models.CharField(max_length=10)
    nullable = models.CharField(max_length=10, null=True)
```
Next two use case:
1. Insert with default null value
```
mutation InsertFoo{
    saveFoo (input:{
        clientMutationId:"1"
        notNull:"value"
    }) {
  	  ...
    }
}
```
2. Update nullable field (set "value"), not_null ignored
```
mutation UpdateFoo{
    saveFoo (input:{
        clientMutationId:"1"
        id:"id"
        nullable: "value"
    }) {
  	  ...
    }
}
```
3. Update nullable field (set null), not_null ignored
```
mutation UpdateFoo{
    saveFoo (input:{
        clientMutationId:"1"
        id:"id"
        nullable: null
    }) {
  	  ...
    }
}
```
How can I use "default_value" to set the nullable field to null (case 3)?

**Comment by syrusakbary** [comment]
Hey @prokofiev, after thinking about this I realized this could be approached in a easier way. As `input` is a `dict`, you could check if  `not_null` in exists in `input`.

Something like
```python
@classmethod
def mutate_and_get_payload(cls, input, context, info):
    not_null = 'UNDEFINED'
    if 'not_null' in input:
        # ....
        not_null = input['not_null']
   # ....
```

Does that make sense?

**Comment by prokofiev** [comment]
Hi @syrusakbary !
It does not make sense because the fields with null values are removed from the argument list and not in the input dict. 
Problem in graphql-core in [this](https://github.com/graphql-python/graphql-core/blob/master/graphql/utils/value_from_ast.py#L6) and [this](https://github.com/graphql-python/graphql-core/blob/master/graphql/execution/values.py#L56) functions.

**Comment by syrusakbary** [comment]
You're right, let me check better what we can do for solve it :)

**Comment by syrusakbary** [comment]
After checking, I realized that this query:

```graphql
mutation UpdateFoo{
    saveFoo (input:{
        clientMutationId:"1"
        id:"id"
        nullable: null
    }) {
      ...
    }
}
```

Is actually not valid as `null` is not a valid value in GraphQL.
https://github.com/graphql-python/graphql-core/blob/master/graphql/language/tests/test_parser.py#L80-L84

For this reason I guess that some client's check when the value is null and then skip it (Relay?).

As an extra exercise, I checked that arguments and input fields that are not provided don't fill the dictionary with None values:

```python
def test_does_not_include_arguments_that_were_not_set():
    InputObject = GraphQLInputObjectType(
        name='InputObject',
        fields={
            'value': GraphQLInputObjectField(GraphQLString, default_value=None),
            'other': GraphQLInputObjectField(GraphQLString, default_value=None)
        }
    )
    def resolver(data, args, *_):
        print args
        return 'other' in args['c']

    schema = GraphQLSchema(GraphQLObjectType(
        'Type',
        {
            'field': GraphQLField(
                GraphQLInt,
                resolver=resolver,
                args={
                    'a': GraphQLArgument(GraphQLBoolean),
                    'b': GraphQLArgument(GraphQLBoolean),
                    'c': GraphQLArgument(InputObject),
                    'd': GraphQLArgument(GraphQLInt),
                    'e': GraphQLArgument(GraphQLInt),
                }
            )
        }
    ))

    ast = parse('{ field(c: {value: "3"}) }')
    result = execute(schema, ast)
    assert result.data == {
        'field': False
    }
```

If you can provide more insights that I might be missing please let me know.

**Comment by prokofiev** [comment]
null value may be passed like this:
```
mutation UpdateFoo($var1:String!){
    saveFoo (input:{
        clientMutationId:"1"
        id:"id"
        nullable: $var1
    }) {
      ...
    }
}
```
variables:
```
{"var1": null}
```

**Comment by nuschk** [comment]
Hey @prokofiev , did you find a workaround for this?

I'm struggling with exactly the same problem and am very interested in your approach. The least hack I could come up with, is to always require all arguments and then use 'input.get('myVar', None)' to retrieve them in 'mutate_and_get_payload()'. 

Even setting the field to be required and having a default value will not make it appear in the input dict...

**Comment by prokofiev** [comment]
Hi @nuschk.
I found solution for my case. It's monkey patch but it works...
You can see my patch [here](https://gist.github.com/prokofiev/039897d7473b0fcf8e65e2b9ce86f94b)
Call apply from any place when initialize your app.

**Comment by prokofiev** [comment]
If somebody knows how to fix it more correctly, please let me know.

**Comment by nuschk** [comment]
@prokofiev Hehe, thanks for the snippet. Will look into it.

**Comment by BossGrand** [comment]
@syrusakbary have you seen this pull request?
https://github.com/facebook/graphql/pull/83

graphql now supports nullable types. Can we get some support for this in graphene?

**Comment by NiekHoekstra** [comment]
Any progress on this?

**Comment by Eraldo** [comment]
@NiekHoekstra Does a PR exist yet for this? If not are you willing to take the patch and turn it into a PR? :)

**Comment by patrickkempff** [comment]
We are having the same problem!

**Comment by BossGrand** [comment]
This issue is solved in graphene 2.0 and should be closed

**Comment by arif-hanif** [comment]
Does someone have an example for 2.0?

**Comment by rdemetrescu** [comment]
@BossGrand  I am still having this problem with null values.
If my javascript client sends a mutation with those variables:
`{"id": 4, "titulo": "TITULO", "resenha": "RESENHA", "autorId": 1}`

my server receives this as **args (at mutate function):
`{'autor_id': 1, 'id': 4, 'resenha': 'RESENHA', 'titulo': 'TITULO'}`

However, if the client sends this:

`{"id": 4, "titulo": "TITULO", "resenha": null, "autorId": null}`

My python **args param receives only 2 keys/values:

`{'id': 4, 'titulo': 'TITULO'}`

(where I would expect receiving `{'id': 4, 'titulo': 'TITULO', 'resenha': None, 'autorId': None}`)

My packages versions:

```
➜ pip freeze | grep -i graph
Flask-GraphQL==1.4.1
graphene==2.0
graphene-sqlalchemy==2.0.0
graphql-core==2.0
graphql-relay==0.4.5
```

Should this issue be reopened ?

Thanks in advance

**Comment by arif-hanif** [comment]
@rdemetrescu i get the same thing... so not sure if this is really fixed.

**Comment by rdemetrescu** [comment]
@arif-hanif, just noticed that [mutations using relay](http://docs.graphene-python.org/en/latest/relay/mutations/) work perfectly.

**Comment by jinty** [comment]
I have seen this query:
```
                mutation myMutation {
                       editIt(Input: {id: "AFJS", title: null}) {
                           It {id}
                       }
                  }
```
fail with:

     'Syntax Error GraphQL request (3:112) Unexpected Name "null"

However when I pass title as a "variable" it does work.

**Comment by jkimbo** [comment]
[graphql-core](https://github.com/graphql-python/graphql-core) is responsible for the query parsing so that is where adding `null` to the language will need to be added. Looks like there is already a pull request open to implement it: https://github.com/graphql-python/graphql-core/pull/119

@rdemetrescu I can't reproduce your issue. If you are still having problems can you open a new issue with everything needed to reproduce it?

Closing this for now

**Comment by brabeji** [comment]
@jkimbo Hi, this is still unsolved and the link to the root issue is dead. Can you please advise where this is/was tracked? Thanks!

**Comment by jkimbo** [comment]
@brabeji we will shortly be releasing graphene v3 that is based on graphql-core v3 which is a complete rewrite and has support for null values. You can try out the beta release now. Release notes are here: https://github.com/graphql-python/graphene/wiki/v3-release-notes

**Comment by laurent-brisbois** [comment]
@jkimbo Hello !
Any luck to see the graphene v3 official release soon to solve this ?

**Comment by JBrVJxsc** [comment]
Need this change as well. It does not make sense to remove null values in the parameters.

**Comment by arghodayah** [comment]
need this as well

**Comment by laurent-brisbois** [comment]
Is there any breaking change in V3 ? Maybe we can use the  latest beta while waiting the official release ?
It is quite annoying at the moment since we cannot unset a variable by sending 'null' from the frontend to the mutation.

**Comment by arghodayah** [comment]
> use for auth

Had same issue, we need to wait for django-graphql-jwt update

**Comment by arghodayah** [comment]
> Is there any breaking change in V3 ? Maybe we can use the latest beta while waiting the official release ?
> It is quite annoying at the moment since we cannot unset a variable by sending 'null' from the frontend to the mutation.
> 
> _Edit:_
> Tried quickly and it seems [django-graphql-jwt](https://github.com/flavors/django-graphql-jwt) which I use for authentication isn't compatible...
> Tried with :
> 
> ```
> django==3.1.5
> psycopg2==2.8.6
> graphene-django==3.0.0b7
> django-graphql-jwt==0.3.1
> PyJWT>=1.5.0,<2
> pyyaml==5.3.1
> gunicorn==20.0.4
> ```
> 
> instead of :
> 
> ```
> django==3.1.5
> psycopg2==2.8.6
> graphene-django==2.15.0
> django-graphql-jwt==0.3.1
> PyJWT>=1.5.0,<2
> pyyaml==5.3.1
> gunicorn==20.0.4
> ```

Had same issue, we need to wait for django-graphql-jwt update
