### ISSUE TITLE
Problem with simple create mutation

### ISSUE THREAD

**Issue by mojochao** [graphql-python/graphene#535]
I'm trying to add a simple create mutation for a SQLAlchemy model and am not having much success.  My code looks like:

```python
import graphene
from graphene.relay import Node
from graphene_sqlalchemy import SQLAlchemyConnectionField, SQLAlchemyObjectType

from sm import models  # module containing my SQLAlchemy model classes

def _make_object_type(class_name, model):
    """Factory function dynamically creating SQLAlchemyObjectType subclasses."""
    def _make_inner_meta_type():
        return type('Meta', (), {'model': model, 'interfaces': (Node, )})
    return type(class_name, (SQLAlchemyObjectType, ), {'Meta': _make_inner_meta_type()})

Company = _make_object_type('Company', models.Company)
# ... lots of other SQLAlchemyObjectType types elided

class Query(graphene.ObjectType):
    node = Node.Field()
    company = Node.Field(Company)
    all_companies = SQLAlchemyConnectionField(Company)
# ... lots of other fields elided

class CompanyInput(graphene.InputObjectType):
    name = graphene.String(required=True)
    description = graphene.Int(required=False)

class CreateCompany(graphene.Mutation):
    class Arguments:
        company_data = CompanyInput(required=True)

    # output fields of mutation
    # ok = graphene.Boolean()
    company = graphene.Field(lambda: Company)

    @staticmethod
    def mutate(root, company_data=None):
        company = Company(
            name=company_data.name,
            description=company_data.description
        )
        return CreateCompany(company=company)

class Mutation(graphene.ObjectType):
    create_company = CreateCompany.Field()

schema = graphene.Schema(query=Query, mutation=Mutation)
```

When I issue the following mutation:

```
mutation myFirstMutation {
    createCompany(companyData: {name:"Test", description: "A test company"}) {
        company {
            name,
            description
        }
    }
}
```

In graphiql I don't see any input type in the docs, and a red squiggle under the companyData argument to createCompany.  When I execute the query I get an error message of "Unknown argument 'companyData' on field 'createCompany' of type 'Mutation'."

I based my attempt on the docs at http://docs.graphene-python.org/en/latest/types/mutations/, and everything seems correct.  Does any one have any idea what I'm doing wrong?

Many thanks in advance!

**Comment by syrusakbary** [comment]
Hi @mojochao,

Sorry, there was a typo on the `2.0` docs that I just fixed with the commit: https://github.com/graphql-python/graphene/commit/74550637280b65179cb897c8386799a9a6776f42.

Everything should run if you add the `info` arg after `root` and before `company_data`.
Like:

```python
    @staticmethod
    def mutate(root, info, company_data=None):
```

Let me know if this works!

**Comment by mojochao** [comment]
Thanks @syrusakbary.  Unfortunately, I'm still seeing the same error.

**Comment by absolutelyNoWarranty** [comment]
@syrusakbary don't know if this is related to @mojochao's issue but the mutation example in the docs doesn't seem to work. I copied and pasted the example from the [documentation on mutations](http://docs.graphene-python.org/en/latest/types/mutations/) into the [playground](http://graphene-python.org/playground/?query=mutation+myFirstMutation+%7B%0A++createPerson%28name%3A+%22Peter%22%29+%7B%0A++++person+%7B%0A++++++name%0A++++%7D%0A++++ok%0A++%7D%0A%7D%0A&schema=import+graphene%0A%0Aclass+CreatePerson%28graphene.Mutation%29%3A%0A++++class+Arguments%3A%0A++++%09name+%3D+graphene.String%28%29%0A%0A++++ok+%3D+graphene.Boolean%28%29%0A++++person+%3D+graphene.Field%28lambda%3A+Person%29%0A%0A++++%40staticmethod%0A++++def+mutate%28root%2C+info%2C+name%29%3A%0A++++++++person+%3D+Person%28name%3Dname%29%0A++++++++ok+%3D+True%0A++++++++return+CreatePerson%28person%3Dperson%2C+ok%3Dok%29%0A++++%0A%23+...+the+Mutation+Class%0A%0Aclass+Person%28graphene.ObjectType%29%3A%0A++++name+%3D+graphene.String%28%29%0A++++age+%3D+graphene.Int%28%29%0A%0Aclass+MyMutations%28graphene.ObjectType%29%3A%0A++++create_person+%3D+CreatePerson.Field%28%29%0A%0A%23+We+must+define+a+query+for+our+schema%0Aclass+Query%28graphene.ObjectType%29%3A%0A++++person+%3D+graphene.Field%28Person%29%0A%0Aschema+%3D+graphene.Schema%28query%3DQuery%2C+mutation%3DMyMutations%29)

and the result is `Unknown argument \"name\" on field \"createPerson\" of type \"MyMutations\".`)

**Comment by mojochao** [comment]
I found that I had to update graphql-core, graphene, and graphene-sqlalchemy to the 2.0.dev versions.  After that, the suggestion made by @syrusakbary worked for me.
